# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b914e35d2bbe9ff3c60de10100837979ce91763691cf6818911c5bf5e89fdae735b9d06e6afedcebc84fe33aa3ff3ac0323f885dd892049f7ef1e8759ecf222

test:
  secret_key_base: 883988c9841f6de375d3d37033005f27502b2ed8c304f5d00c6572aff4a5e906e66dc42e6f01c8e3dc62f27efa917a6adf916ae019a6f11d68a1d5ece3e4636b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
